

# This file was *autogenerated* from the file rsatogether.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_65537 = Integer(65537); _sage_const_101 = Integer(101); _sage_const_0 = Integer(0); _sage_const_2048 = Integer(2048); _sage_const_99 = Integer(99); _sage_const_3 = Integer(3); _sage_const_8 = Integer(8)#!/usr/bin/env sage

from Crypto.Util.number import getPrime, bytes_to_long
import random
import os

random = random.SystemRandom()

flag = os.getenv("FLAG", "ECSC{testflag}")

def gen_key(n_bits):
    p = getPrime(n_bits//_sage_const_2 )
    q = getPrime(n_bits//_sage_const_2 )
    n = p*q
    phi = (p-_sage_const_1 )*(q-_sage_const_1 )
    e = _sage_const_65537 
    d = pow(e, -_sage_const_1 , phi)

    return phi, d, n, e

def eval_poly(poly, x, n):
    return sum(pow(x, i, n) * poly[i] for i in range(len(poly))) % n

def create_shares(phi, poly):
    n_shares = int(input("With how many friends you want to share the private key? "))

    if n_shares < _sage_const_1 :
        print("Don't be mean, sharing is caring!")
        exit()
    elif n_shares > _sage_const_101 :
        print("Come on, you don't have that many friends...")
        exit()

    n_shares += _sage_const_1  # you also get one part of the key, don't worry
    poly = poly[:n_shares]
    ys = [eval_poly(poly, i, phi) for i in range(_sage_const_1 , n_shares+_sage_const_1 )]
    M = matrix(ZZ, [[x**i for i in range(n_shares)] for x in range(_sage_const_1 , n_shares+_sage_const_1 )])
    coeffs = M.solve_left(vector(ZZ, [_sage_const_1 ] + [_sage_const_0 ]*(n_shares - _sage_const_1 )))

    shares = [(c*y) % phi for c,y in zip(coeffs, ys)]
    yours = shares.pop(n_shares - _sage_const_2 )
    print(f"Here is your part: {yours}")

    return shares


def comput_partial_decryption(c, shares, n):
    return [pow(c, s, n) for s in shares]


n_bits = _sage_const_2048 
phi, d, n, e = gen_key(n_bits)
print(f"{n = }")
print(f"{e = }")

poly = [d] + [random.getrandbits(n_bits) for _ in range(_sage_const_99 )]
shares = create_shares(phi, poly)

while True:
    choice = int(input("""
Select:
1) Decrypt something
2) Reshare
3) That's enough
> """))
    if choice == _sage_const_1 :
        c = int(input("Ciphertext: "))
        partial_dec = comput_partial_decryption(c, shares, n)
        print("Here are the partial decryptions of your friends!")
        for pt in partial_dec:
            print(pt)
    elif choice == _sage_const_2 :
        shares = create_shares(phi, poly)
    elif choice == _sage_const_3 :
        break

pad_flag = os.urandom((n_bits - _sage_const_8 )//_sage_const_8  - len(flag)) + flag.encode()
print(f"Bye bye, take this with you!\n{pow(bytes_to_long(pad_flag), e , n)}")

